name: Clojure CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: clj-kondo checks
      uses: DeLaGuardo/clojure-lint-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: npm install
      uses: Jaid/action-npm-install@v1.2.4
    - name: shadow-cljs build
      uses: vouch-opensource/tools.deps-build@1.0.1
      with:
        alias: cljs:ci
