name: Clojure CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: clj-kondo checks
      uses: DeLaGuardo/clojure-lint-action@v1
      with:
        # Github token to report linter results back to check
        github_token: ${{ secrets.GITHUB_TOKEN }}
